Page({
  data:{
    info1 :[
            {
                "about": "进修于日本好莱坞专科学院n中国知名美发教育“魔鬼训练营总教练”n中国知名美发学院立体裁剪首席讲师n担任上海市中心高端日系连锁店的技术教育总监。SupperShow沙龙创始人n14年进修日本宫村浩气团队美感造型设计n16年进修日本山野美发学院潮流剪烫染",
                "address": null,
                "hdid": "上海",
                "expertise": "#教育导师,店长,剪裁给力,绅士服务, 日系,善于沟通",
                "skype": "@LiSen老师风格教育wechat13564159767",
                "saddress": "上海江浦路紫荆广场附近",
                "hlog": "121.47320",
                "hlat": "31.23406",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "1000米以内",
                "kmstr": 715.483813495024,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": "上海市",
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 680,
                "blogcou": 941.0,
                "ise": 1,
                "identity": null,
                "WxImpression": null,
                "uid": "27fae280-c2fb-42e5-94de-68a2acd25140",
                "nickname": "LiSen独创动感空气打薄",
                "sex": 0,
                "cell": "13564159767",
                "logo": "/uploadimg/16/11/30/161130122031665.jpg",
                "sign": null,
                "hbid": "上海",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "成功，最快的捷径就是模仿。",
                "address": null,
                "hdid": "上海",
                "expertise": "发现美，创造美。",
                "skype": null,
                "saddress": "淮海中路927弄56号",
                "hlog": "121.47485",
                "hlat": "31.23346",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "1000米以内",
                "kmstr": 604.34606137993808,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 220,
                "blogcou": 905.0,
                "ise": 1,
                "identity": null,
                "WxImpression": null,
                "uid": "ca94154e-68ee-4cc0-9d43-ff3bf653a125",
                "nickname": "____安藤Ando",
                "sex": 0,
                "cell": "15800411109",
                "logo": "/uploadimg/14/10/08/141008000153606.jpg",
                "sign": null,
                "hbid": "NewFashion发型定制",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造型还包括一些上海时装周，FEELING等活动提供专业美发造型2011年：2013年：型尚美发学院担任校长2014年创办了昕和传承教育共享平台",
                "address": null,
                "hdid": "上海",
                "expertise": "",
                "skype": null,
                "saddress": "长宁区定西路739号明旺大厦4F",
                "hlog": "121.464183",
                "hlat": "31.225394",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "2000米以内",
                "kmstr": 1951.655981769138,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 0,
                "blogcou": 23.0,
                "ise": 1,
                "identity": null,
                "WxImpression": null,
                "uid": "e28cca1e-d20f-4206-bfcb-b0d38215e4ac",
                "nickname": "King",
                "sex": 0,
                "cell": "15021666661",
                "logo": "/uploadimg/13/10/11/131011160735811.jpg",
                "sign": null,
                "hbid": "昕和传承教育共享平台",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造",
                "address": null,
                "hdid": "其它城市",
                "expertise": "",
                "skype": null,
                "saddress": null,
                "hlog": "121.48565",
                "hlat": "31.25491",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "3000米以内",
                "kmstr": 2125.2429017946988,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 0,
                "blogcou": 1.0,
                "ise": 1,
                "identity": null,
                "WxImpression": null,
                "uid": "00be81ba-5b08-4eae-a5d5-a84e6852f57c",
                "nickname": "德嘉商学院",
                "sex": 0,
                "cell": "10000120072",
                "logo": "/uploadimg/16/10/31/161031163757811.jpg",
                "sign": null,
                "hbid": "其他城市",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造",
                "address": null,
                "hdid": "其它城市",
                "expertise": "",
                "skype": null,
                "saddress": null,
                "hlog": "121.48560",
                "hlat": "31.25551",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "3000米以内",
                "kmstr": 2188.878822665064,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 0,
                "blogcou": 0.0,
                "ise": 1,
                "identity": null,
                "WxImpression": null,
                "uid": "191f0709-9f1f-4b7e-810a-224110ecfd92",
                "nickname": "共想学院",
                "sex": 0,
                "cell": "10000120074",
                "logo": "/uploadimg/16/09/26/160926130808602.jpg",
                "sign": null,
                "hbid": "其他城市",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造",
                "address": null,
                "hdid": "其它城市",
                "expertise": "",
                "skype": null,
                "saddress": null,
                "hlog": "121.48787",
                "hlat": "31.25444",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "3000米以内",
                "kmstr": 2136.6563733711287,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 0,
                "blogcou": 0.0,
                "ise": 1,
                "identity": null,
                "WxImpression": null,
                "uid": "2600678d-15a2-4d42-afbc-16f6c07966b0",
                "nickname": "华尔推剪",
                "sex": 0,
                "cell": "10000120065",
                "logo": "/uploadimg/16/11/07/161107142412121.jpg",
                "sign": null,
                "hbid": "其他城市",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造",
                "address": null,
                "hdid": "上海",
                "expertise": "#剪裁给力,日系,烫发专家,帅气",
                "skype": "擅长短发，中发，日系修剪造型……",
                "saddress": "杨浦区大学路56号302室kingstudio鑫潮形象",
                "hlog": "121.48000",
                "hlat": "31.22700",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "2000米以内",
                "kmstr": 1039.2246878068233,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 198,
                "blogcou": 183.0,
                "ise": 2,
                "identity": null,
                "WxImpression": null,
                "uid": "fd1ab0ea-41c5-4675-869f-9e9bb109744b",
                "nickname": "Jeffrey",
                "sex": 0,
                "cell": "18202114085",
                "logo": "/uploadimg/17/03/09/170309174105171.jpg",
                "sign": null,
                "hbid": "上海",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "人物风格形象定位，设计理念是根据人物自身的风格体现，和你喜欢的风格的结合！设计细节会根据你的脸型、头型、肤色、身材比例、性格、年龄和一些你喜欢的穿衣风格等等因素，来跟你量身定制属于你自己的专属发型.n2015年加入阿玛尼，2015年东方卫视风从东方来后台造型，2015年中国城市春晚后台造型，进修过沙宣ABC，欧莱雅三星整体造型师，欧莱雅色彩五星，对与发型设计有自己独到的见解.n周三休息不接受预约",
                "address": null,
                "hdid": "上海",
                "expertise": "#剪裁给力,整体设计,有品味,善于沟通,日系,色彩玩家,日韩范,烫发专家,教育导师,颜值高",
                "skype": "你身边的私人形象定制设计师Eric",
                "saddress": "上海市浦东东绣路467号",
                "hlog": "121.47604",
                "hlat": "31.22704",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "2000米以内",
                "kmstr": 1108.7674248734183,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 158,
                "blogcou": 11.0,
                "ise": 2,
                "identity": null,
                "WxImpression": null,
                "uid": "96afa914-4363-4317-8c18-fd6b77e632cd",
                "nickname": "Eric李增辉",
                "sex": 0,
                "cell": "15721352580",
                "logo": "/uploadimg/17/05/06/170506181355211.jpg",
                "sign": null,
                "hbid": "AMANI锦绣店",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "马丁老师，，专业发型设计师，有着自己独有的设计理念，曾进修于多加美发教育机构，擅长各种风格剪裁，接合自己的绘画技艺，，，针对每个人的个人特点进行风格分析，定位，，，沟通线描设计，，担任多位艺人的形象顾问！",
                "address": "淡水路213-1号",
                "hdid": "上海",
                "expertise": "#剪裁给力,好打理,善于沟通,色彩玩家, 烫发专家,日系,有品味",
                "skype": null,
                "saddress": "淡水路214弄",
                "hlog": "121.47323",
                "hlat": "31.21749",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "3000米以内",
                "kmstr": 2198.8928000484489,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 128,
                "blogcou": 871.0,
                "ise": 0,
                "identity": null,
                "WxImpression": null,
                "uid": "7e42a6fb-c08c-4a10-9ca3-25c579348588",
                "nickname": "翠步摇，，，马丁",
                "sex": 0,
                "cell": "15921082389",
                "logo": "/uploadimg/14/01/23/140123201136185.jpg",
                "sign": null,
                "hbid": "翠步摇",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "8000起保底工资，上海高端专业美发连锁东瀛造型8千起保底招幕发型师，要求发型师经验5年以上，形象技术好，我们店都在上海最好的商场，剪发价位128至500元，每天5个以上客人，联系人：平总监电话：17302165195微信cuifeng1360",
                "address": null,
                "hdid": "上海",
                "expertise": "#颜值高,剪裁给力,日系,绅士服务,善于沟通",
                "skype": "上海高端专业美发东瀛造型8千保底招幕发型",
                "saddress": "湖北路20号中信福申大楼A座14楼",
                "hlog": "121.47810",
                "hlat": "31.23351",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "500米以内",
                "kmstr": 375.37274882033472,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 380,
                "blogcou": 511.0,
                "ise": 0,
                "identity": null,
                "WxImpression": null,
                "uid": "500115bb-4418-4f41-a19f-3ba890276d7b",
                "nickname": "东瀛国际造型",
                "sex": 0,
                "cell": "13601883345",
                "logo": "/uploadimg/17/02/24/170224102443325.jpg",
                "sign": null,
                "hbid": "上海",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造",
                "address": null,
                "hdid": "上海",
                "expertise": "#剪裁给力",
                "skype": "复杂的结构源于简单的线条",
                "saddress": "上海市新广路241号",
                "hlog": "121.47735",
                "hlat": "31.25684",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "3000米以内",
                "kmstr": 2293.0521388710713,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 128,
                "blogcou": 429.0,
                "ise": 0,
                "identity": null,
                "WxImpression": null,
                "uid": "7b094c37-f063-4898-9f61-d1edc07cfad7",
                "nickname": "桃子",
                "sex": 1,
                "cell": "13636593856",
                "logo": "/uploadimg/16/10/29/161029102159463.jpg",
                "sign": null,
                "hbid": "艺语沙龙",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造",
                "address": null,
                "hdid": "合肥",
                "expertise": "",
                "skype": null,
                "saddress": "近河南中路,地铁2号、10号线南京东路站3号出口，电梯直达五楼宏伊国际广场右转即到",
                "hlog": "121.47408",
                "hlat": "31.23769",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "1000米以内",
                "kmstr": 603.68856634513088,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 0,
                "blogcou": 335.0,
                "ise": 0,
                "identity": null,
                "WxImpression": null,
                "uid": "f51bdcd7-74a7-4009-97ab-c2b2743aea3b",
                "nickname": "东瀛造型COCO",
                "sex": 0,
                "cell": "13917478808",
                "logo": "/uploadimg/15/06/09/150609130718491.jpg",
                "sign": null,
                "hbid": "合肥",
                "salonlng": null,
                "salonlat": null
            },
            {
                "about": "2007年-2008年：获得第六届巴黎欧莱雅色彩成就奖全国总冠军2008年：加入巴黎欧莱雅专业美发创意小组2009年：1）加入东田造型，担任技术总监2）巴黎欧莱雅专业美发中国创意小组唯一赴法国巴黎卢浮宫举行国际发型潮流演出《ChinainParis》。与HCF法国高级发型师美发协会的明星发型师们同台演出2009年-2010年：多次为中国具有影响力的杂志《ELLE》《时尚先生》《时尚COSMOPOLITAN》《听薇》《艾丝》等提供美发造",
                "address": null,
                "hdid": "上海",
                "expertise": "",
                "skype": null,
                "saddress": "南京西路梅龙镇广场501c",
                "hlog": "121.46636",
                "hlat": "31.22845",
                "fans": null,
                "customer": null,
                "tips": null,
                "km": "2000米以内",
                "kmstr": 1584.0488161690764,
                "badgeprelist": null,
                "isopen": 0,
                "salonuid": null,
                "bgimage": null,
                "slon": null,
                "slat": null,
                "notice": null,
                "mos": null,
                "price": 400,
                "blogcou": 270.0,
                "ise": 0,
                "identity": null,
                "WxImpression": null,
                "uid": "67f482e7-b0c7-48dc-802f-1b695e546fda",
                "nickname": "王磊美发：ken丁彪",
                "sex": 0,
                "cell": "18301963586",
                "logo": "/uploadimg/15/02/13/150213122833788.jpg",
                "sign": null,
                "hbid": "王磊形象设计",
                "salonlng": null,
                "salonlat": null
            }]
  },
  onLoad:function(options){
    // 生命周期函数--监听页面加载
    console.log(options)
      console.log(options.uid)
  },
  onReady:function(){
    // 生命周期函数--监听页面初次渲染完成
    
  },
  onShow:function(){
    // 生命周期函数--监听页面显示
    
  },
  onHide:function(){
    // 生命周期函数--监听页面隐藏
    
  },
  onUnload:function(){
    // 生命周期函数--监听页面卸载
    
  },
  onPullDownRefresh: function() {
    // 页面相关事件处理函数--监听用户下拉动作
    
  },
  onReachBottom: function() {
    // 页面上拉触底事件的处理函数
    
  },
  onShareAppMessage: function() {
    // 用户点击右上角分享
    return {
      title: 'title', // 分享标题
      desc: 'desc', // 分享描述
      path: 'path' // 分享路径
    }
  },
  getindex:function(e){
      var id=e.target.dataset.index
      wx.makePhoneCall({
        phoneNumber:id
      })
  }
})